export const DEMO_GIGS = [
  {
    id: 'g1',
    title: 'Summer Festival Promoters',
    eventType: 'Music Festival',
    description: 'We need 20 energetic promoters for a major summer music festival. Must be enthusiastic and good with crowds.',
    city: 'Johannesburg',
    venue: 'Marks Park, Emmarentia',
    eventDate: '15-16 Feb 2025',
    talentNeeded: 20,
    categories: ['Promoter', 'Brand Ambassador'],
    compensation: 'R1,500/day',
    interestCount: 8,
  },
  {
    id: 'g2',
    title: 'Luxury Brand Launch Hostesses',
    eventType: 'Brand Launch',
    description: 'Exclusive product launch for a premium fashion brand. Looking for sophisticated hostesses with luxury event experience.',
    city: 'Cape Town',
    venue: 'V&A Waterfront',
    eventDate: '8 Mar 2025',
    talentNeeded: 8,
    categories: ['Hostess', 'Model'],
    compensation: 'R2,000/evening',
    interestCount: 5,
  },
  {
    id: 'g3',
    title: 'Corporate Golf Day Models',
    eventType: 'Golf Day',
    description: 'Annual corporate golf day. Need models for registration, beverage service, and prize-giving ceremony.',
    city: 'Pretoria',
    venue: 'Silver Lakes Golf Estate',
    eventDate: '22 Mar 2025',
    talentNeeded: 6,
    categories: ['Model', 'Hostess'],
    compensation: 'R1,800/day',
    interestCount: 3,
  },
  {
    id: 'g4',
    title: 'LIV Golf South Africa - Event Hostesses & Ambience Models',
    eventType: 'Golf Day',
    description: 'LIV Golf is coming to South Africa! We need 30 premium hostesses and ambience models for a 3-day international golf tournament. Roles include VIP hospitality lounge hosting, player registration, beverage cart models, branded activation stands, and on-course ambience. Must be professional, well-groomed, and comfortable in an upscale international sporting environment. International media exposure guaranteed.',
    city: 'Johannesburg',
    venue: 'The Wanderers Club, Illovo',
    eventDate: '12-14 Apr 2025',
    talentNeeded: 30,
    categories: ['Model', 'Hostess', 'Ambience', 'Brand Ambassador'],
    compensation: 'R3,500/day',
    interestCount: 18,
  },
  {
    id: 'g5',
    title: 'SAICA Engineering Golf Day - Hostesses & Registration Models',
    eventType: 'Golf Day',
    description: 'Annual SAICA Engineering charity golf day at the prestigious Houghton Golf Club. Need 10 professional hostesses and models for player registration, hole sponsorship activations, beverage service on course, and prize-giving ceremony hosting. Corporate dress code. Must be punctual, articulate, and comfortable engaging with senior executives and professionals.',
    city: 'Johannesburg',
    venue: 'Houghton Golf Club',
    eventDate: '5 May 2025',
    talentNeeded: 10,
    categories: ['Hostess', 'Model', 'Brand Ambassador'],
    compensation: 'R2,200/day',
    interestCount: 6,
  },
];