export type DemoMember = {
  id: string;
  name: string;
  company: string;
  role: string;
  phone: string;
  email: string;
  city: string;
};

export const DEMO_MEMBERS: Record<string, DemoMember[]> = {
  corporate: [
    {
      id: 'corp-1',
      name: 'Sipho Ndlovu',
      company: 'Platinum Events Corp',
      role: 'Director',
      phone: '+27821234567',
      email: 'sipho@platinumcorp.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'corp-2',
      name: 'Amanda van der Merwe',
      company: 'ABN Group',
      role: 'Marketing Manager',
      phone: '+27839876543',
      email: 'amanda@abngroup.co.za',
      city: 'Cape Town',
    },
    {
      id: 'corp-3',
      name: 'Rajesh Patel',
      company: 'Patel Holdings',
      role: 'CEO',
      phone: '+27761234567',
      email: 'rajesh@patelholdings.co.za',
      city: 'Durban',
    },
    {
      id: 'corp-4',
      name: 'Thabo Mokoena',
      company: 'Standard Bank Events',
      role: 'Events Director',
      phone: '+27841112233',
      email: 'thabo.mokoena@standardbank.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'corp-5',
      name: 'Lauren Smit',
      company: 'Coca-Cola SA',
      role: 'Brand Manager',
      phone: '+27832345678',
      email: 'lauren.smit@coca-cola.co.za',
      city: 'Johannesburg',
    },
  ],
  golf_days: [
    {
      id: 'em-1',
      name: 'Nandi Mkhize',
      company: 'NM Events & Productions',
      role: 'Owner',
      phone: '+27821112233',
      email: 'nandi@nmevents.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'em-2',
      name: 'Pierre du Plessis',
      company: 'Eventful SA',
      role: 'Director',
      phone: '+27839988776',
      email: 'pierre@eventfulsa.co.za',
      city: 'Cape Town',
    },
    {
      id: 'em-3',
      name: 'Busisiwe Dube',
      company: 'Busi Events & Decor',
      role: 'Managing Director',
      phone: '+27762223344',
      email: 'busi@busievents.co.za',
      city: 'Durban',
    },
    {
      id: 'em-4',
      name: 'Craig Thompson',
      company: 'CT Event Solutions',
      role: 'Partner',
      phone: '+27843334455',
      email: 'craig@ctevents.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'em-5',
      name: 'Zanele Khumalo',
      company: 'ZK Productions',
      role: 'Founder',
      phone: '+27834445566',
      email: 'zanele@zkproductions.co.za',
      city: 'Pretoria',
    },
  ],
  restaurants: [
    {
      id: 'rest-1',
      name: 'Marco Rossi',
      company: 'The Palazzo Restaurant',
      role: 'General Manager',
      phone: '+27821122334',
      email: 'marco@thepalazzo.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'rest-2',
      name: 'Fatima Ismail',
      company: 'Spice Kitchen',
      role: 'Owner',
      phone: '+27839988776',
      email: 'fatima@spicekitchen.co.za',
      city: 'Durban',
    },
    {
      id: 'rest-3',
      name: 'David Wilson',
      company: 'The Test Kitchen',
      role: 'Events Manager',
      phone: '+27762233445',
      email: 'david@testkitchen.co.za',
      city: 'Cape Town',
    },
    {
      id: 'rest-4',
      name: 'Nomsa Molefe',
      company: 'Ubuntu Cuisine',
      role: 'Director',
      phone: '+27843344556',
      email: 'nomsa@ubuntucuisine.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'rest-5',
      name: 'James Anderson',
      company: 'The Butcher Shop & Grill',
      role: 'Owner',
      phone: '+27834455667',
      email: 'james@thebutchershop.co.za',
      city: 'Johannesburg',
    },
  ],
  agencies: [
    {
      id: 'ag-1',
      name: 'Thabiso Mahlangu',
      company: 'Prestige Models SA',
      role: 'CEO',
      phone: '+27821133445',
      email: 'thabiso@prestigemodels.co.za',
      city: 'Johannesburg',
    },
    {
      id: 'ag-2',
      name: 'Claire Botha',
      company: 'Cape Talent Agency',
      role: 'Director',
      phone: '+27839977665',
      email: 'claire@capetalent.co.za',
      city: 'Cape Town',
    },
    {
      id: 'ag-3',
      name: 'Michael Nkosi',
      company: 'Urban Talent SA',
      role: 'Founder',
      phone: '+27762244556',
      email: 'michael@urbantalent.co.za',
      city: 'Durban',
    },
    {
      id: 'ag-4',
      name: 'Sarah van Zyl',
      company: 'Elite Events Agency',
      role: 'Managing Director',
      phone: '+27843355667',
      email: 'sarah@eliteagency.co.za',
      city: 'Pretoria',
    },
    {
      id: 'ag-5',
      name: 'Lungile Dlamini',
      company: 'Afri-Talent Connect',
      role: 'Partner',
      phone: '+27834466778',
      email: 'lungile@afritalent.co.za',
      city: 'Johannesburg',
    },
  ],
};