const IMG = 'https://api.a0.dev/assets/image';

function tImg(desc: string, seed: number) {
  return `${IMG}?text=${encodeURIComponent(desc)}&aspect=3:4&seed=${seed}`;
}

export const MOCK_TALENT = [
  {
    _id: 'demo_t1' as any,
    _creationTime: Date.now() - 86400000 * 5,
    userId: 'demo_u_t1' as any,
    firstName: 'Naledi',
    lastName: 'Mokoena',
    phone: '+27 82 345 6789',
    city: 'Johannesburg',
    area: 'Sandton',
    race: 'Black',
    bodyType: 'Slim',
    heightCm: 172,
    bio: 'Professional model and hostess with 5 years of experience in the South African event and fashion industry. Worked with brands including Castle Lite, MTN, and Woolworths. Passionate about delivering exceptional brand representation.',
    categories: ['Model', 'Hostess', 'Brand Ambassador'],
    photoUrls: [
      tImg('professional portrait beautiful african female model elegant studio lighting', 101),
      tImg('full body african female model gold evening dress studio', 102),
      tImg('african female model casual outdoor Johannesburg photoshoot', 103),
    ],
    status: 'approved',
    instagram: 'naledi_m',
    tiktok: '',
    declineReason: '',
  },
  {
    _id: 'demo_t2' as any,
    _creationTime: Date.now() - 86400000 * 3,
    userId: 'demo_u_t2' as any,
    firstName: 'Chantelle',
    lastName: 'van Wyk',
    phone: '+27 76 111 2233',
    city: 'Cape Town',
    area: 'Sea Point',
    race: 'White',
    bodyType: 'Athletic',
    heightCm: 168,
    bio: 'Dynamic promoter and brand ambassador based in Cape Town. Experienced in activations, in-store promotions, and corporate events. Energetic, professional, and great with crowds.',
    categories: ['Promoter', 'Brand Ambassador'],
    photoUrls: [
      tImg('professional portrait beautiful blonde female model athletic Cape Town studio', 201),
      tImg('blonde female promoter at brand activation event smiling', 202),
    ],
    status: 'approved',
    instagram: 'chantelle_vw',
    tiktok: '',
    declineReason: '',
  },
  {
    _id: 'demo_t3' as any,
    _creationTime: Date.now() - 86400000 * 1,
    userId: 'demo_u_t3' as any,
    firstName: 'Zinhle',
    lastName: 'Dlamini',
    phone: '+27 83 222 4455',
    city: 'Durban',
    area: 'Umhlanga',
    race: 'Black',
    bodyType: 'Curvy',
    heightCm: 170,
    bio: 'Hostess and bottle girl with experience at premium nightlife venues and VIP events across KZN. Confident, well-presented, and great at engaging guests.',
    categories: ['Hostess', 'Bottle Girl'],
    photoUrls: [
      tImg('professional portrait beautiful african female model glamorous Durban studio', 301),
      tImg('african female hostess elegant black dress VIP lounge', 302),
    ],
    status: 'pending',
    instagram: 'zinhle_d',
    tiktok: 'zinhle_d',
    declineReason: '',
  },
  {
    _id: 'demo_t4' as any,
    _creationTime: Date.now() - 86400000 * 7,
    userId: 'demo_u_t4' as any,
    firstName: 'Thandi',
    lastName: 'Mabaso',
    phone: '+27 71 333 5566',
    city: 'Pretoria',
    area: 'Centurion',
    race: 'Black',
    bodyType: 'Athletic',
    heightCm: 175,
    bio: 'Fashion model and brand ambassador with runway experience at SA Fashion Week. Fitness enthusiast and content creator. Available for photoshoots, fashion shows, and brand campaigns.',
    categories: ['Model', 'Brand Ambassador'],
    photoUrls: [
      tImg('professional portrait beautiful african female model tall athletic elegant studio', 401),
      tImg('african female model fashion runway backstage', 402),
      tImg('african female model fitness lifestyle outdoor', 403),
    ],
    status: 'approved',
    instagram: 'thandi_mabaso',
    tiktok: '',
    declineReason: '',
  },
  {
    _id: 'demo_t5' as any,
    _creationTime: Date.now() - 86400000 * 2,
    userId: 'demo_u_t5' as any,
    firstName: 'Priya',
    lastName: 'Naidoo',
    phone: '+27 84 444 7788',
    city: 'Durban',
    area: 'Ballito',
    race: 'Indian',
    bodyType: 'Slim',
    heightCm: 163,
    bio: 'Promoter and corporate event hostess. Fluent in English and Hindi. Experience with pharmaceutical launches, tech conferences, and trade exhibitions.',
    categories: ['Promoter', 'Hostess'],
    photoUrls: [
      tImg('professional portrait beautiful indian female model elegant studio lighting', 501),
      tImg('indian female promoter corporate event professional attire', 502),
    ],
    status: 'pending',
    instagram: 'priya_n',
    tiktok: '',
    declineReason: '',
  },
  {
    _id: 'demo_t6' as any,
    _creationTime: Date.now() - 86400000 * 10,
    userId: 'demo_u_t6' as any,
    firstName: 'Kayla',
    lastName: 'September',
    phone: '+27 79 555 9900',
    city: 'Cape Town',
    area: 'Stellenbosch',
    race: 'Coloured',
    bodyType: 'Slim',
    heightCm: 169,
    bio: 'Model and promoter with experience in wine estate events, food festivals, and outdoor brand activations across the Western Cape. Bilingual in English and Afrikaans.',
    categories: ['Model', 'Promoter'],
    photoUrls: [
      tImg('professional portrait beautiful mixed race female model elegant Cape Town studio', 601),
      tImg('mixed race female model wine estate outdoor photoshoot', 602),
      tImg('mixed race female promoter brand activation outdoor event', 603),
    ],
    status: 'approved',
    instagram: 'kayla_sept',
    tiktok: 'kayla_sept',
    declineReason: '',
  },
];

export const MOCK_GIGS = [
  {
    _id: 'demo_g1' as any,
    _creationTime: Date.now() - 86400000 * 2,
    title: 'Summer Festival Promoters',
    description: 'We need 20 energetic and well-presented promoters for a major summer music festival in Johannesburg. Duties include crowd engagement, brand sampling, and social media content creation. Must be comfortable in outdoor settings and available for the full weekend.',
    eventType: 'Music Festival',
    city: 'Johannesburg',
    venue: 'Marks Park, Emmarentia',
    eventDate: '15-16 February 2025',
    talentNeeded: 20,
    categories: ['Promoter', 'Brand Ambassador'],
    requirements: 'Must be energetic, comfortable outdoors, available for full weekend',
    compensation: 'R1,500 per day',
    status: 'open',
    createdBy: 'demo_admin' as any,
    interestCount: 8,
  },
  {
    _id: 'demo_g2' as any,
    _creationTime: Date.now() - 86400000 * 5,
    title: 'Luxury Brand Launch Hostesses',
    description: 'Exclusive product launch for a premium fashion brand at the V&A Waterfront. Looking for sophisticated, well-spoken hostesses to greet VIP guests, manage guest lists, and provide product information.',
    eventType: 'Brand Launch',
    city: 'Cape Town',
    venue: 'V&A Waterfront',
    eventDate: '8 March 2025',
    talentNeeded: 8,
    categories: ['Hostess', 'Model'],
    requirements: 'Min 168cm, elegant appearance, well-spoken',
    compensation: 'R2,000 for the evening',
    status: 'open',
    createdBy: 'demo_admin' as any,
    interestCount: 5,
  },
  {
    _id: 'demo_g3' as any,
    _creationTime: Date.now() - 86400000 * 8,
    title: 'Corporate Golf Day Models',
    description: 'Annual corporate golf day at a premier golf estate. Need models for tee-off registration, beverage service at selected holes, and prize-giving ceremony. Smart-casual dress code.',
    eventType: 'Golf Day',
    city: 'Pretoria',
    venue: 'Silver Lakes Golf Estate',
    eventDate: '22 March 2025',
    talentNeeded: 6,
    categories: ['Model', 'Hostess'],
    requirements: 'Professional demeanour, comfortable with corporate clients',
    compensation: 'R1,800 for the day',
    status: 'open',
    createdBy: 'demo_admin' as any,
    interestCount: 3,
  },
];

export const MOCK_BOOKINGS = [
  {
    _id: 'demo_b1' as any,
    _creationTime: Date.now() - 86400000 * 1,
    clientId: 'demo_u_client' as any,
    clientName: 'Michael Dube',
    clientCompany: 'Elevation Events',
    clientPhone: '+27 82 555 1234',
    clientEmail: 'michael@elevationevents.co.za',
    talentCount: 5,
    eventType: 'Brand Activation',
    eventDate: '28 February 2025',
    city: 'Johannesburg',
    venue: 'Sandton City Mall',
    requirements: 'Promoters for tech brand activation. Must be tech-savvy and engaging.',
    status: 'pending',
    talentIds: ['demo_t1', 'demo_t2', 'demo_t4', 'demo_t6'] as any[],
    notes: '',
  },
  {
    _id: 'demo_b2' as any,
    _creationTime: Date.now() - 86400000 * 4,
    clientId: 'demo_u_client2' as any,
    clientName: 'Sarah van der Merwe',
    clientCompany: 'Cape Fashion Group',
    clientPhone: '+27 71 888 4567',
    clientEmail: 'sarah@capefashion.co.za',
    talentCount: 8,
    eventType: 'Fashion Show',
    eventDate: '20 March 2025',
    city: 'Cape Town',
    venue: 'Cape Town International Convention Centre',
    requirements: 'Models min 170cm for runway. Experience preferred.',
    status: 'confirmed',
    talentIds: ['demo_t1', 'demo_t4', 'demo_t6'] as any[],
    notes: 'Confirmed with all selected talent. Final fitting on 18 March.',
  },
  {
    _id: 'demo_b3' as any,
    _creationTime: Date.now() - 86400000 * 6,
    clientId: 'demo_u_client' as any,
    clientName: 'Michael Dube',
    clientCompany: 'Elevation Events',
    clientPhone: '+27 82 555 1234',
    clientEmail: 'michael@elevationevents.co.za',
    talentCount: 3,
    eventType: 'Conference',
    eventDate: '10 April 2025',
    city: 'Durban',
    venue: 'Durban ICC',
    requirements: 'Registration desk hostesses. Professional appearance required.',
    status: 'reviewed',
    talentIds: ['demo_t3', 'demo_t5'] as any[],
    notes: 'Under review, reaching out to talent.',
  },
];

// For client's "My Bookings" view
export const MOCK_MY_BOOKINGS = [
  {
    _id: 'demo_b1' as any,
    _creationTime: Date.now() - 86400000 * 1,
    eventType: 'Brand Activation',
    eventDate: '28 February 2025',
    status: 'pending',
    talentCount: 5,
    city: 'Johannesburg',
    venue: 'Sandton City Mall',
  },
  {
    _id: 'demo_b3' as any,
    _creationTime: Date.now() - 86400000 * 6,
    eventType: 'Conference',
    eventDate: '10 April 2025',
    status: 'reviewed',
    talentCount: 3,
    city: 'Durban',
    venue: 'Durban ICC',
  },
];

// For admin: booking talent details
export const MOCK_BOOKING_TALENT = [
  {
    _id: 'demo_t1' as any,
    firstName: 'Naledi',
    lastName: 'Mokoena',
    photoUrl: tImg('professional portrait beautiful african female model elegant studio lighting', 101),
    city: 'Johannesburg',
    heightCm: 172,
    race: 'Black',
    phone: '+27 82 345 6789',
    instagram: 'naledi_m',
  },
  {
    _id: 'demo_t4' as any,
    firstName: 'Thandi',
    lastName: 'Mabaso',
    photoUrl: tImg('professional portrait beautiful african female model tall athletic elegant studio', 401),
    city: 'Pretoria',
    heightCm: 175,
    race: 'Black',
    phone: '+27 71 333 5566',
    instagram: 'thandi_mabaso',
  },
  {
    _id: 'demo_t6' as any,
    firstName: 'Kayla',
    lastName: 'September',
    photoUrl: tImg('professional portrait beautiful mixed race female model elegant Cape Town studio', 601),
    city: 'Cape Town',
    heightCm: 169,
    race: 'Coloured',
    phone: '+27 79 555 9900',
    instagram: 'kayla_sept',
  },
];

// For admin: gig interest details (talent who expressed interest)
export const MOCK_GIG_INTERESTS = [
  {
    _id: 'demo_t1' as any,
    firstName: 'Naledi',
    lastName: 'Mokoena',
    phone: '+27 82 345 6789',
    city: 'Johannesburg',
    area: 'Sandton',
    race: 'Black',
    bodyType: 'Slim',
    heightCm: 172,
    categories: ['Model', 'Hostess', 'Brand Ambassador'],
    photoUrls: [
      tImg('professional portrait beautiful african female model elegant studio lighting', 101),
      tImg('full body african female model gold evening dress studio', 102),
    ],
    instagram: 'naledi_m',
    note: '',
  },
  {
    _id: 'demo_t4' as any,
    firstName: 'Thandi',
    lastName: 'Mabaso',
    phone: '+27 71 333 5566',
    city: 'Pretoria',
    area: 'Centurion',
    race: 'Black',
    bodyType: 'Athletic',
    heightCm: 175,
    categories: ['Model', 'Brand Ambassador'],
    photoUrls: [
      tImg('professional portrait beautiful african female model tall athletic elegant studio', 401),
      tImg('african female model fashion runway backstage', 402),
    ],
    instagram: 'thandi_mabaso',
    note: 'Available for full weekend',
  },
  {
    _id: 'demo_t6' as any,
    firstName: 'Kayla',
    lastName: 'September',
    phone: '+27 79 555 9900',
    city: 'Cape Town',
    area: 'Stellenbosch',
    race: 'Coloured',
    bodyType: 'Slim',
    heightCm: 169,
    categories: ['Model', 'Promoter'],
    photoUrls: [
      tImg('professional portrait beautiful mixed race female model elegant Cape Town studio', 601),
      tImg('mixed race female model wine estate outdoor photoshoot', 602),
    ],
    instagram: 'kayla_sept',
    note: '',
  },
];

// For talent: my gig interests
export const MOCK_MY_INTERESTS = [
  {
    gigId: 'demo_g1' as any,
    gigTitle: 'Summer Festival Promoters',
    gigCity: 'Johannesburg',
    gigDate: '15-16 February 2025',
    interestStatus: 'interested',
    gigStatus: 'open',
  },
  {
    gigId: 'demo_g2' as any,
    gigTitle: 'Luxury Brand Launch Hostesses',
    gigCity: 'Cape Town',
    gigDate: '8 March 2025',
    interestStatus: 'selected',
    gigStatus: 'open',
  },
];

export const MOCK_CLIENT_PROFILE = {
  _id: 'demo_cp1' as any,
  companyName: 'Elevation Events',
  contactPerson: 'Michael Dube',
  phone: '+27 82 555 1234',
  email: 'michael@elevationevents.co.za',
};

export function getDemoUser(role: string) {
  switch (role) {
    case 'admin':
      return { _id: 'demo_admin' as any, name: 'Diamond Angels Admin', email: 'admin@diamondangels.co.za', role: 'admin', image: undefined };
    case 'client':
      return { _id: 'demo_u_client' as any, name: 'Michael Dube', email: 'michael@elevationevents.co.za', role: 'client', image: undefined };
    case 'talent':
      return { _id: 'demo_u_t1' as any, name: 'Naledi Mokoena', email: 'naledi@gmail.com', role: 'talent', image: undefined };
    default:
      return null;
  }
}
